version: '3.8'

services:
  postgresdb:
    platform: linux
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: unless-stopped
    image: stayfinder-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$DB_NAME",
        "spring.datasource.username": "$DB_USER",
        "spring.datasource.password": "$DB_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
